env:
  browser: true
  es6: true
extends:
  - prettier
plugins:
  - flowtype
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: {}
